# Training config
DATASET: "myDataset"
SEQ_LEN: 128
MAX_FILES: 10
BATCH_SIZE: 32
LEARNING_RATE: 0.001
EPOCHS: 50

# Generation Config
NUM_PREDICTIONS: 120
TEMPERATURE: 1.5
TIME_STRETCH: 1.5
INSTRUMENT_NAME: "Acoustic Grand Piano"

# Classical Specs
CLASSICAL_MODEL_PATH: "outputs/models/test.pt"
CLASSICAL_SEED_DIR: "myDataset"
CLASSICAL_OUTPUT_PATH: "outputs/music/test.mid"

# Quantum Specs
QUANTUM_MODEL_PATH: "outputs/models/memory/iqp_rnn_10.pt"
QUANTUM_SEED_DIR: "myDataset"
QUANTUM_OUTPUT_PATH: "outputs/music/memory/test.mid"
