# Training config
DATASET: "../maestro-v3.0.0"
SEQ_LEN: 32
MAX_FILES: 1
BATCH_SIZE: 32
LEARNING_RATE: 0.0005
EPOCHS: 50

# Generation Config
NUM_PREDICTIONS: 120
TEMPERATURE: 1.0
TIME_STRETCH: 1.15
INSTRUMENT_NAME: "Acoustic Grand Piano"

# Classical Specs
CLASSICAL_MODEL_PATH: "outputs/models/music_rnn.pt"
CLASSICAL_SEED_DIR: "../maestro-v3.0.0"
CLASSICAL_OUTPUT_PATH: "outputs/music/output.mid"

# Quantum Specs
QUANTUM_MODEL_PATH: "outputs/models/quantum_rnn_10.pt"
QUANTUM_SEED_DIR: "../maestro-v3.0.0"
QUANTUM_OUTPUT_PATH: "outputs/music/quantum_output_10.mid"
