# Training config
DATASET: "../maestro-v3.0.0"
SEQ_LEN: 64
MAX_FILES: 100
BATCH_SIZE: 32
LEARNING_RATE: 0.0005
EPOCHS: 50

# Generation Config
NUM_PREDICTIONS: 120
TEMPERATURE: 1.25
TIME_STRETCH: 2.0
INSTRUMENT_NAME: "Acoustic Grand Piano"

# Classical Specs
CLASSICAL_MODEL_PATH: "outputs/models/music_rnn.pt"
CLASSICAL_SEED_DIR: "../maestro-v3.0.0"
CLASSICAL_OUTPUT_PATH: "outputs/music/output.mid"

# Quantum Specs
QUANTUM_MODEL_PATH: "outputs/models/memory/quantum_rnn_100.pt"
QUANTUM_SEED_DIR: "../maestro-v3.0.0"
QUANTUM_OUTPUT_PATH: "outputs/music/memory/quantum_output_10_1.mid"
